title: Dery Ferdika
logo: "/Images/dery.jpg?raw=true"
description: 
  <p align="center">
  <a href="pdf/CV Dery.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/deryferdikaoktoriansah/">LinkedIn</a> |
  <a href="https://github.com/DeryFerd">GitHub</a>
  </p>
  
  <p align="justify">
  I am undergraduate student in Universitas Negeri Malang, Indonesia. My major is Mathematics.
  <br><br>
  I am currently learn Data Analytics at Zenius with a focus on SQL and Python.
  <br><br>
  </p>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
