title: Dery Ferdika
logo: <img src="Images/dummy_thumbnail.jpg?raw=true"/>
description: 
    first description
    <br><br>
    Hi, my name is Dery.
    <br><br>
    second description
    <br><br>
    <a href="https://www.linkedin.com/in/deryferdikaoktoriansah/">View My LinkedIn Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
