title: Dery Ferdika
logo: "/assets/img/wony.jpeg?raw=true"
description: 
    first description
    <br><br>
    Leo Messi is better than Cristiano Ronaldo.
    <br><br>
    second description
    <br><br>
    <a href="https://www.linkedin.com/in/deryferdikaoktoriansah/">View My LinkedIn Profile</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
