title: Dery Ferdika
logo: "/Images/dery.jpg?raw=true"
description: 
    first description
    <br><br>
    Hi, my name is Dery.
    <br><br>
    second description
    <br><br>
    <a href="https://www.linkedin.com/in/deryferdikaoktoriansah/">View My LinkedIn Profile</a>
    <br><br>
    <a href="pdf/CV Dery.pdf">View My Resume</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
